delete http://localhost:3003/api/posts/5d5d1fd2a395f148e0e5dba2
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjVkNzM1MzNhZDkyYTEzNTZjYzI4OTFiYiIsImlhdCI6MTU2Nzg1MjA4OX0.IbmjidNYtEcCFkfDSB5ga6o3_MC_PTDImyUthV-GEWU
